### PR TITLE
#138 Adding terms&conditions checkbox

### PR DESCRIPTION
**Pull request by edu11**
#138

### CODE REVIEW

**Comment by edu11** [comment]
Hi @ptyagicodecamp, have you checked this PR?

**Comment by ptyagicodecamp** [comment]
@edu11 : did you get chance to look at my previous comment on this PR ?
"do we want terms check box "checked" by default. usually I've noticed that its better to leave it unchecked and put user in charge to agree to ToC."

**Comment by edu11** [comment]
Sorry @ptyagicodecamp, I haven't seen any comment till now...
I've run and checked this PR code and the checkbox is not checked by default, user has to agree ToC in order to continue registration process as the first time the registration is shown, the checkbox is unchecked. I'm not sure I've understood what you mean...

**Comment by ptyagicodecamp** [comment]
looks good in another glance on code. I think i read it wrong first time.

**Pull request merged**
